# Generated by Django 5.1.3 on 2024-11-06 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=65)),
                (
                    'wallet',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='transactions',
                        to='wallets.wallet')
                ),
            ],
            options={
                'db_table': 'finances_transactions',
                'ordering': ('-id',),
            },
        ),
    ]
