"""Wallets and Transactions

Revision ID: 781cc5328eb8
Revises: 
Create Date: 2024-11-07 19:33:50.352594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781cc5328eb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finances_wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.Column('balance', sa.DECIMAL(precision=65, scale=18), nullable=True),
    sa.CheckConstraint('balance >= 0', name='wallet_balance_cant_be_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finances_wallets_balance'), 'finances_wallets', ['balance'], unique=False)
    op.create_index(op.f('ix_finances_wallets_label'), 'finances_wallets', ['label'], unique=False)
    op.create_table('finances_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('txid', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=65, scale=18), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['finances_wallets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txid')
    )
    op.create_index(op.f('ix_finances_transactions_amount'), 'finances_transactions', ['amount'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finances_transactions_amount'), table_name='finances_transactions')
    op.drop_table('finances_transactions')
    op.drop_index(op.f('ix_finances_wallets_label'), table_name='finances_wallets')
    op.drop_index(op.f('ix_finances_wallets_balance'), table_name='finances_wallets')
    op.drop_table('finances_wallets')
    # ### end Alembic commands ###
